import App from './App.uvue'

import { createSSRApp } from 'vue'
export function createApp() {
	const app = createSSRApp(App)
	app.mixin({
		data(){
			return {
				globalMsg: 'default Msg'
			}
		},
		watch: {
			globalMsg(newVal){
				console.log('watch in main.uts--------globalMsg changed newVal: ', newVal)
				this.title = newVal
			}
		},
		methods: {
			globalMethod(){
				console.log('globalMethod')
				this.globalMsg = 'globalMsg'
			}
		}
	})
	return {
		app
	}
}